// packages/ori-web-app/ui-presets/solid/src/App.jsx
/* @jsxImportSource solid-js */
import { createSignal } from "solid-js";

export default function App() {
  const [count, setCount] = createSignal(0);
  return (
    <main style={{ "font-family": "system-ui", "max-width": "32rem", margin: "2rem auto", padding: "0 1rem" }}>
      <h1>Solid + Ori</h1>
      <p>Official UI preset. Build into <code>public/</code>.</p>
      <button type="button" onClick={() => setCount(count() + 1)}>
        Clicks: {count()}
      </button>
    </main>
  );
}

// packages/ori-web-app/ui-presets/vue/src/App.vue
<script setup>
import { ref } from "vue";
const count = ref(0);
</script>

<template>
  <main>
    <h1>Vue + Ori</h1>
    <p>Official UI preset. Build into <code>public/</code>.</p>
    <button @click="count++">Clicks: {{ count }}</button>
  </main>
</template>

<style scoped>
main { font-family: system-ui, sans-serif; max-width: 32rem; margin: 2rem auto; padding: 0 1rem; }
button { font: inherit; padding: 0.5rem 0.9rem; border-radius: 0.5rem; border: 1px solid #ccc; cursor: pointer; }
</style>
